# =================================================================
# Configuration file for model run.
# =================================================================

# Path to SWMM .inp file.
swmm_path: ~/SWMM/model.inp

# Model component values.
# Set model component values with same units as the simulation.

# Link parameters. Put the link number and parameter value under the corresponding section.
link:
  max_depth:
    1: 3.5
    2: 2

  length:
    1: 4000

# Node parameters.
node:
  depth:
    1: 6

# Subcatchment parameters.
subcatchment:
  perc_impervious:
    10: 25


# Precipitation.
timeseries:
  ts1:
    name: TS1
    filepath: None
    hours: [0, 1, 2, 3, 4, 5, 6]
    values: [0, 1, 0.8, 0.6, 0.4, 0.2, 0]

  ts2:
    name: TS2
    filepath: None
    hours: [ 0, 1, 2, 3, 4, 5, 6 ]
    values: [ 0, 1, 0.8, 0.6, 0.4, 0.2, 0 ]


# Rain gauge.
rain_gauge:
  rg1:
    timeseries: TS1

  rg2:
    timeseries: TS2






