# =================================================================
# Configuration file for model run.
# =================================================================

# Path to SWMM .inp file.
swmm_path: ~/SWMM/model.inp

# Model component values.
# Set model component values with same units as the simulation.

# Conduit/link parameters. Put the link number and parameter value under the corresponding section.
CONDUITS:
  # Diameter of the conduits (termed "depth") in feet.
  depth:
    2: 3

  # Manning's roughness of the conduits.
  roughness:
    2: 0.02

  # Length of the conduits in feet.
  length:

# Node/junction parameters.
JUNCTIONS:
  # Depth of the nodes below the surface.
  max_depth:

  # Elevation of the node.
  invert_elevation:

# Subcatchment parameters.
SUBCATCHMENTS:
  perc_impervious:


# Precipitation.
timeseries:
  ts1:
    name: TS1
    filepath: None
    hours: [0, 1, 2, 3, 4, 5, 6]
    values: [0, 1, 0.8, 0.6, 0.4, 0.2, 0]

  ts2:
    name: TS2
    filepath: None
    hours: [ 0, 1, 2, 3, 4, 5, 6 ]
    values: [ 0, 1, 0.8, 0.6, 0.4, 0.2, 0 ]


# Rain gauge.
rain_gauge:
  rg1:
    timeseries: TS1

  rg2:
    timeseries: TS2






